version: '3.8'

volumes:
  postgres_data:
    driver: local
#  pgadmin_data:
#    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init/01-init.sh:/docker-entrypoint-initdb.d/init-db.sh # used only first time container is built to create database and users
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=admin"
      - "KEYCLOAK_DB=keycloak"
      - "KEYCLOAK_DB_USER=keycloak"
      - "KEYCLOAK_DB_PASSWORD=keycloak"
      - "KEYCLOAK_DB_SCHEMA=keycloak"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4
#    hostname: pgadmin4
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: shahrooz.sabet@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - ${GLOBAL_NETWORK:-postgres}
#  keycloak-authorization-server:
#    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
#    container_name: keycloak
#    hostname: keycloak-server
#    ports:
#      - "8081:8081"
#    environment:
#      - "KEYCLOAK_USER=admin"
#      - "KEYCLOAK_PASSWORD=admin"
#      - "KEYCLOAK_LOGLEVEL=DEBUG"
#      - "JAVA_OPTS=-Djboss.http.port=8081"
#      - "DB_VENDOR=POSTGRES"
#      - "DB_ADDR=postgres"
#      - "DB_DATABASE=keycloak"
#      - "DB_USER=keycloak"
#      - "DB_SCHEMA=public"
#      - "DB_PASSWORD=keycloak"
#    depends_on:
#      - postgres